routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LenguajesDeProgramacionController;
use App\Http\Controllers\FrameworksController;
use App\Http\Controllers\ProyectosController;

Route::get('/', function () {return view('welcome');});
Route::get('/lenguajes-de-programacion', [LenguajesDeProgramacionController::class, 'index']);
Route::get('/frameworks', [FrameworksController::class, 'index']);
Route::get('/proyectos/{id}', [ProyectosController::class, 'show']);

app/Models/Framework.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class Framework extends Model
{
    protected $table = 'frameworks';
    protected $fillable = ['nombre', 'version', 'pagina_web_url', 'logo_url', 'lenguaje_programacion_id'];

    public function lenguajeProgramacion()
    {
        return $this->belongsTo(LenguajeDeProgramacion::class, 'lenguaje_programacion_id');
    }

    public function proyectos()
    {
        return $this->belongsToMany(Proyecto::class, 'frameworks_por_proyectos', 'framework_id', 'proyecto_id')
                    ->withPivot('descripcion')
                    ->withTimestamps();
    }
};

app/Models/FrameworkPorProyecto.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Relations\Pivot;

class FrameworkPorProyecto extends Pivot
{
    protected $table = 'frameworks_por_proyectos';
    protected $fillable = ['framework_id', 'proyecto_id', 'descripcion'];

    // Asegúrate de definir las relaciones inversas si es necesario
    public function framework()
    {
        return $this->belongsTo(Framework::class, 'framework_id');
    }

    public function proyecto()
    {
        return $this->belongsTo(Proyecto::class, 'proyecto_id');
    }
}

app/Models/LenguajeDeProgramacion.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class LenguajeDeProgramacion extends Model
{
    protected $table = 'lenguajes_de_programacion';
    protected $fillable = ['nombre', 'version', 'activo'];

    public function frameworks()
    {
        return $this->hasMany(Framework::class, 'lenguaje_programacion_id');
    }

    // Para contar los proyectos relacionados con los frameworks de este lenguaje de programación
    public function proyectosCount()
    {
        return $this->frameworks()
                    ->join('frameworks_por_proyectos', 'frameworks.id', '=', 'frameworks_por_proyectos.framework_id')
                    ->join('proyectos', 'frameworks_por_proyectos.proyecto_id', '=', 'proyectos.id')
                    ->selectRaw('count(distinct proyectos.id) as proyectos_count')
                    ->groupBy('frameworks.lenguaje_programacion_id');
    }
};

app/Models/Proyecto.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Proyecto extends Model
{
    use HasFactory;
    protected $table = 'proyectos';
    protected $fillable = ['nombre', 'fecha_desde', 'fecha_hasta', 'activo', 'descripcion', 'encargado'];

    protected $casts = [
        'activo' => 'boolean',
        'fecha_desde' => 'date',
        'fecha_hasta' => 'date',
    ];

    public function frameworks()
    {
        return $this->belongsToMany(Framework::class, 'frameworks_por_proyectos', 'proyecto_id', 'framework_id')
                    ->withPivot('descripcion')
                    ->withTimestamps();
    }
};

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/FrameworksController.php
<?php
namespace App\Http\Controllers;
use App\Models\Framework;
use Illuminate\Http\Request;

class FrameworksController extends Controller
{
    public function index(Request $request)
    {
        $query = Framework::with(['lenguajeProgramacion', 'proyectos']);

        if ($request->has('search')) {
            $query->where('nombre', 'ILIKE', '%' . $request->search . '%');
        }

        if ($request->has('lenguaje_id')) {
            $query->where('lenguaje_programacion_id', $request->lenguaje_id);
        }

        $frameworks = $query->get();

        return view('frameworks.index', compact('frameworks'));
    }
}

app/Http/Controllers/FrameworksPorProyectosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FrameworksPorProyectosController extends Controller
{
    //
}

app/Http/Controllers/LenguajesDeProgramacionController.php
<?php
namespace App\Http\Controllers;
use App\Models\LenguajeDeProgramacion;
use Illuminate\Http\Request;

class LenguajesDeProgramacionController extends Controller
{
    public function index(Request $request)
    {
        $query = LenguajeDeProgramacion::withCount('frameworks');

        if ($request->has('search')) {
            $query->where('nombre', 'ILIKE', '%' . $request->search . '%');
        }

        if ($request->has('activo')) {
            $activo = filter_var($request->activo, FILTER_VALIDATE_BOOLEAN);
            $query->where('activo', $activo);
        }

        $lenguajes = LenguajeDeProgramacion::withCount('frameworks')->get();

        foreach ($lenguajes as $lenguaje) {
            // Hay que ver si el tema de la consulta de proyectosCount() se ejecuta correctamente
            $proyectosCount = $lenguaje->proyectosCount()->get();
            $lenguaje->proyectos_count = $proyectosCount->first()->proyectos_count ?? 0;
        }

        return view('lenguajes.index', compact('lenguajes'));
    }

    public function showWelcome()
    {
        $lenguajesCount = LenguajeDeProgramacion::count();
        return view('welcome', compact('lenguajesCount'));
    }
};

app/Http/Controllers/ProyectosController.php
<?php
namespace App\Http\Controllers;
use App\Models\Proyecto;
use App\Models\Framework;
use Illuminate\Http\Request;

class ProyectosController extends Controller
{
    public function show($id)
    {
        $proyecto = Proyecto::with(['frameworks', 'frameworks.lenguajeProgramacion'])
                            ->findOrFail($id);

        return view('proyectos.show', compact('proyecto'));
    }
}

resources/views/frameworks/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Listado de Frameworks</h2>
    <form action="{{ url('/frameworks') }}" method="GET">
        <input type="text" name="search" placeholder="Buscar por nombre...">
        <button type="submit">Buscar</button>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Lenguaje de Programación</th>
                <th>Imagen</th>
                <th>Número de Proyectos</th>
                <th>Proyectos Asociados</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($frameworks as $framework)
                <tr>
                    <td>{{ $framework->nombre }}</td>
                    <td>{{ $framework->lenguajeProgramacion->nombre }}</td>
                    <td>
                        <a href="{{ $framework->pagina_web_url }}" target="_blank">
                            <img src="{{ $framework->logo_url }}" alt="{{ $framework->nombre }}" style="width: 50px; height: auto;">
                        </a>
                    </td>
                    <td>{{ $framework->proyectos->count() }}</td>
                    <td>
                        @foreach ($framework->proyectos as $proyecto)
                            <a href="{{ url('/proyectos/'.$proyecto->id) }}">{{ $proyecto->nombre }}</a><br>
                        @endforeach
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <a href="{{ url('/') }}" class="btn btn-primary">Volver al inicio</a>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dev Project</title>
        <link href="{{ asset('styles/bootstrap.min.css') }}" rel="stylesheet">
    </head>

    <body>
        <main class="py-4">
            @yield('content')
        </main>

        <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    </body>
</html>

resources/views/lenguajes/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Listado de Lenguajes de Programación</h2>

        <form style="margin: 20px 0px" action="{{ url('/lenguajes-de-programacion') }}" method="GET">
            <input type="text" name="search" placeholder="Buscar por nombre">

            <select name="activo">
                <option value="">Todos</option>
                <option value="1">Activo</option>
                <option value="0">Inactivo</option>
            </select>
            <button type="submit">Buscar</button>
        </form>

        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Version</th>
                    <th>Estado</th>
                    <th>Número de Frameworks</th>
                    <th>Número de Proyectos</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($lenguajes as $lenguaje)
                    <tr>
                        <td>{{ $lenguaje->nombre }}</td>
                        <td>{{ $lenguaje->version }}</td>
                        <td><span class="badge {{ $lenguaje->activo ? 'bg-success' : 'bg-danger' }}">{{ $lenguaje->activo ? 'Activo' : 'Inactivo' }}</span></td>
                        <td>{{ $lenguaje->frameworks_count }}</td>
                        <td>{{ $lenguaje->proyectos_count }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <a href="{{ url('/') }}" class="btn btn-primary">Volver al inicio</a>
    </div>
@endsection

resources/views/proyectos/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card border-primary mb-3" style="border-width: 2px; margin: 20px 0px">
            <div class="card-body">
                <h3 class="card-title">{{ $proyecto->nombre }}</h3>
                <p class="card-text">{{ $proyecto->descripcion }}</p>
                <p>Encargado: {{ $proyecto->encargado }}</p>
                <p>Fecha de inicio: {{ $proyecto->fecha_desde->format('d/m/Y') }}</p>
                <p>Fecha de finalización: {{ $proyecto->fecha_hasta->format('d/m/Y') }}</p>
                <span class="badge {{ $proyecto->activo ? 'bg-success' : 'bg-danger' }}">
                    {{ $proyecto->activo ? 'Activo' : 'Inactivo' }}
                </span>

                <h4>Frameworks Utilizados</h4>
                @foreach ($proyecto->frameworks as $framework)
                    <span class="badge bg-success">
                        {{ $framework->nombre }} - {{ $framework->pivot->descripcion }}
                    </span>
                @endforeach

                <h4>Lenguajes de Programación</h4>
                @php
                    $lenguajes = $proyecto->frameworks->map->lenguajeProgramacion->unique('id');
                @endphp
                @foreach ($lenguajes as $lenguaje)
                    <span class="badge bg-info">
                        {{ $lenguaje->nombre }}
                    </span>
                @endforeach
            </div>
        </div>

        <a href="{{ url('/frameworks') }}" class="btn btn-primary mt-3">Volver a la lista</a>
    </div>
@endsection